### Create a new user
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "asd"
}

### Sign in as an existing user
POST  http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "asd"
}

### Get the currently signed in user
GET  http://localhost:3000/auth/whoami


### Sign Out
POST  http://localhost:3000/auth/signout


### Find a particular user with given ID
GET  http://localhost:3000/auth/1


### Find all users with given ID
GET http://localhost:3000/auth?email=test1@test.com


### Delete a user with given ID
DELETE http://localhost:3000/auth/2


### Update a user
PATCH http://localhost:3000/auth/1456
content-Type: application/json

{
  "email": "tugs@tugs.com"
}


